#!/bin/sh
sqlplus64 "username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

DROP TABLE USER_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE RECORD CASCADE CONSTRAINTS;
DROP TABLE SHOOTER CASCADE CONSTRAINTS;
DROP TABLE VICTIM CASCADE CONSTRAINTS;
DROP TABLE US_STATE CASCADE CONSTRAINTS;
exit;
EOF