#!/bin/sh
sqlplus64 "username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

INSERT INTO US_STATE VALUES ('ALABAMA', '168265', '26',  '261');
INSERT INTO US_STATE VALUES ('ALASKA','20520','3', '494');
INSERT INTO US_STATE VALUES ('ARIZONA','204817','4', '326');
INSERT INTO US_STATE VALUES ('ARKANSAS','108801', '15', '228');
INSERT INTO US_STATE VALUES ('CALIFORNIA','376666', '5', '448');
INSERT INTO US_STATE VALUES ('TEXAS', '108493', '9',  '232');
INSERT INTO US_STATE VALUES ('NEW_YORK','21340','22', '494');
INSERT INTO US_STATE VALUES ('ILLINOIS','19273','5', '290');
INSERT INTO US_STATE VALUES ('FLORIDA','101023', '6', '452');
INSERT INTO US_STATE VALUES ('MICHIGAN','237192', '3', '293');
 
INSERT INTO SHOOTER VALUES ('SH1', 'ROBERT BENJAMIN', 'SMITH', '18', 'MALE','WHITE','PISTOL',NULL, 'ARIZONA');
INSERT INTO SHOOTER VALUES ('SH2', 'SEDRICK', 'NORRIS', '36', 'MALE','BLACK','RIFLE',NULL, 'ALABAMA');
INSERT INTO SHOOTER VALUES ('SH3', 'MARIO', 'TONY', '20', 'MALE','BLACK','PISTOL','STUDENT', 'ARKANSAS');
INSERT INTO SHOOTER VALUES ('SH4', NULL, 'JONES', '23', 'MALE','WHITE','HANDGUN',NULL, 'CALIFORNIA');
INSERT INTO SHOOTER VALUES ('SH5', 'EVAN', 'RAMSEY', '16', 'MALE','WHITE','SHOTGUN','STUDENT', 'ALASKA');
INSERT INTO SHOOTER VALUES ('SH6', 'ARCHIBALD', 'WISE', '39', 'MALE','WHITE','HANDGUN',NULL, 'ARIZONA');
INSERT INTO SHOOTER VALUES ('SH7', 'HARRY', 'MARAT', '21', 'MALE','BLACK','RIFLE','STUDENT', 'TEXAS');
INSERT INTO SHOOTER VALUES ('SH8', NULL, 'POLLINGER', '34', 'MALE','BLACK','PISTOL',NULL, 'NEW_YORK');
INSERT INTO SHOOTER VALUES ('SH9', NULL, 'HANSON', '23', 'MALE','WHITE','PISTOL',NULL, 'FLORIDA');
INSERT INTO SHOOTER VALUES ('SH10', 'JOHNATHAN', 'AUDREY', '19', 'MALE','BLACK','SHOTGUN','STUDENT', 'MICHIGAN');
 
INSERT INTO VICTIM VALUES ('VIC1', 'ROSE', 'ALEXANDER', 'FEMALE', NULL, 'ARIZONA', 'SH1');
INSERT INTO VICTIM VALUES ('VIC2', NULL, 'NORRIS', 'FEMALE', '35', 'ALABAMA', 'SH2');
INSERT INTO VICTIM VALUES ('VIC3', 'JAMIE', 'WILLINGER', 'MALE', '16', 'ARKANSAS', 'SH3');
INSERT INTO VICTIM VALUES ('VIC4', NULL, 'FITZGERALD', 'MALE', NULL, 'CALIFORNIA', 'SH4');
INSERT INTO VICTIM VALUES ('VIC5', 'JOHNATHAN', 'MILLS', 'MALE', '19', 'ALASKA', 'SH5');
INSERT INTO VICTIM VALUES ('VIC6', 'ANTHONY', 'MAVIS', 'MALE', NULL, 'ARIZONA', 'SH6');
INSERT INTO VICTIM VALUES ('VIC7', 'MARTHA', 'FINNIGAN', 'FEMALE', '24', 'TEXAS', 'SH7');
INSERT INTO VICTIM VALUES ('VIC8', 'HOLDEN', 'COOPER', 'MALE', '19', 'FLORIDA', 'SH8');
INSERT INTO VICTIM VALUES ('VIC9', NULL, 'CHUNG', 'FEMALE', '37', 'MICHIGAN', 'SH9');
INSERT INTO VICTIM VALUES ('VIC10', 'REENA', 'SHAH', 'MALE', '45', 'NEW_YORK', 'SH10');

INSERT INTO RECORD VALUES ('RCD1', 'SCHOOL', 'NOVEMBER', '2018', 'VIC1');
INSERT INTO RECORD VALUES ('RCD2', 'RESIDENTIAL', 'MAY', '2017', 'VIC2');
INSERT INTO RECORD VALUES ('RCD3', 'SCHOOL', 'OCTOBER', '2018', 'VIC3');
INSERT INTO RECORD VALUES ('RCD4', 'MASS', 'JANUARY', '2019', 'VIC4');
INSERT INTO RECORD VALUES ('RCD5', 'SCHOOL', 'MARCH', '2019', 'VIC5');
INSERT INTO RECORD VALUES ('RCD6', 'SCHOOL', 'NOVEMBER', '2018', 'VIC6');
INSERT INTO RECORD VALUES ('RCD7', 'RESIDENTIAL', 'FEBRUARY', '2019', 'VIC7');
INSERT INTO RECORD VALUES ('RCD8', 'MASS', 'JULY', '2020', 'VIC8');
INSERT INTO RECORD VALUES ('RCD9', 'SCHOOL', 'DECEMBER', '2017', 'VIC9');
INSERT INTO RECORD VALUES ('RCD10', 'MASS', 'JANUARY', '2018', 'VIC10');
 
INSERT INTO USER_ACCOUNT VALUES ('JEREMY','HIGGINS', '32', 'MALE','JHIGGINS@GMAIL.COM','RCD1');
INSERT INTO USER_ACCOUNT VALUES ('ELAINE','MURPHY', '19', 'FEMALE','ELMURPHY20S@GMAIL.COM','RCD2');
INSERT INTO USER_ACCOUNT VALUES ('SELENA','GARCIA', '24', 'FEMALE','SELG123@GMAIL.COM','RCD3');
INSERT INTO USER_ACCOUNT VALUES ('MIHAIL','NOTAH', '28', 'MALE','MIHAILNOTAH99@GMAIL.COM','RCD4');
INSERT INTO USER_ACCOUNT VALUES ('YONAH','RAYWOOD', '45', 'MALE','YOHANRAYWOOD@GMAIL.COM','RCD5');
INSERT INTO USER_ACCOUNT VALUES ('SOFIA','VIENNA', '19', 'FEMALE','SOFIAV99@GMAIL.COM','RCD6');
INSERT INTO USER_ACCOUNT VALUES ('BRIANNA','WRIGHT', '29', 'FEMALE','BRIBRIWRIGHT@GMAIL.COM','RCD7');
INSERT INTO USER_ACCOUNT VALUES ('PANAMA','MILLIGAN', '38', 'FEMALE','PANMILLI@GMAIL.COM','RCD8');
INSERT INTO USER_ACCOUNT VALUES ('HASSAN','SHAHID', '21', 'MALE','HASSANSHAHID@GMAIL.COM','RCD9');
INSERT INTO USER_ACCOUNT VALUES ('SID','WALLID', '52', 'MALE','SIDWAL@GMAIL.COM','RCD10');
exit;

EOF