--Simple Queries
SELECT * FROM SHOOTER 
WHERE AGE <= 30;

SELECT TYPE_OF_SHOOTING, MONTH_OF_SHOOTING, YEAR_OF_SHOOTING 
FROM RECORD 
WHERE YEAR_OF_SHOOTING = 2019;

SELECT * 
FROM US_STATE
WHERE REGISTERED_WEAPONS > 200000;

SELECT GENDER, AGE, STATE_NAME 
FROM VICTIM 
WHERE AGE >=19;

SELECT * 
FROM USER_ACCOUNT 
WHERE NOT(GENDER = 'FEMALE');

SELECT DISTINCT STATE_NAME AS WEALTHY_STATES
FROM US_STATE
WHERE POLICE_BUDGET_PER_CAPITA > '300'
ORDER BY STATE_NAME;

SELECT record.record_id, victim.state_name
FROM record
INNER JOIN victim ON record.victim_id = victim.victim_id;

SELECT SHOOTER_ID, LAST_NAME, AGE, GENDER, RACE, STATE_NAME
FROM SHOOTER
WHERE (RACE = 'BLACK' AND STATE_NAME = 'ARIZONA')
OR
(RACE = 'WHITE' AND STATE_NAME = 'ARIZONA');